services:
# Utils
    oka_file.doctrine_behaviors.reflection.class_analyzer:
        class:  Oka\FileBundle\DoctrineBehaviors\Reflection\ClassAnalyzer
        public: false

# Doctrine behaviors
    oka_file.doctrine_behaviors.abstract_listener:
        public: false
        abstract: true
        class:  Oka\FileBundle\DoctrineBehaviors\ORM\AbstractListener
        arguments: [ [], '' ]
#        arguments: [ '@oka_file.doctrine_behaviors.reflection.class_analyzer', '%oka_file.doctrine_behaviors.reflection.is_recursive%' ]
        calls:
          - [ setClassAnalyzer, [ '@oka_file.doctrine_behaviors.reflection.class_analyzer' ] ]
          - [ setRecursive, [ '%oka_file.doctrine_behaviors.reflection.is_recursive%' ] ]

    oka_file.doctrine_behaviors.picturecoverizable_listener:
        class:  Oka\FileBundle\DoctrineBehaviors\ORM\PictureCoverizable\PictureCoverizableListener
        parent: oka_file.doctrine_behaviors.abstract_listener
        tags:
            - { name: doctrine.event_subscriber }

    oka_file.doctrine_behaviors.avatarizable_listener:
        class:  Oka\FileBundle\DoctrineBehaviors\ORM\Avatarizable\AvatarizableListener
        parent: oka_file.doctrine_behaviors.abstract_listener
        tags:
            - { name: doctrine.event_subscriber }
