Oka\FileBundle\Model\File:
    type: mappedSuperclass
    fields:
        name:
            type: string
        mimeType:
            name: mime_type
            type: string
            nullable: true
        extension:
            type: string
            nullable: true
        size:
            type: int
        createdAt:
            name: created_at
            type: date
        updatedAt:
            name: updated_at
            type: date
#    lifecycleCallbacks:
#        prePersist: ['setLastModified']
#        preUpdate: ['setLastModified']
