Oka\FileBundle\Model\File:
    type: mappedSuperclass
    indexes:
        mime_type_idx:
            columns: [mime_type]
    fields:
        name:
            type: string
        mimeType:
            column: mime_type
            type: string
            nullable: true
        extension:
            type: string
            nullable: true
        size:
            type: bigint
            options:
                unsigned: true
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime
#    lifecycleCallbacks:
#        prePersist: ['setLastModified']
#        preUpdate: ['setLastModified']
