Oka\FileBundle\Model\File:
    type: mappedSuperclass
    fields:
        name:
            type: string
        mimeType:
            name: mime_type
            type: string
        extension:
            type: string
            nullable: true
        size:
            type: int
            options:
                unsigned: true
        createdAt:
            name: created_at
            type: date
        updatedAt:
            name: updated_at
            type: date
