services:
# Factory
    oka_file.object_manager:
        public: false
        class: Doctrine\Common\Persistence\ObjectManager

# Listener
    Oka\FileBundle\Doctrine\FileListener:
        arguments: ['@oka_file.storage_handler', '@event_dispatcher']
