services:
    Oka\FileBundle\Command\:
        resource: '../../Command/*'
        tags: ['console.command']

    Oka\FileBundle\Command\ContainerCreateCommand:
        arguments: ['@oka_file.container_parameter_bag', '@oka_file.storage_handler']
        tags: ['console.command']
