services:
#    Oka\FileBundle\Command\:
#        resource: '../../Command/*'
#        tags: ['console.command']

#    Oka\FileBundle\Command\ConfigureContainerCommand:
#        arguments: ['%oka_file.storage.root_path%', '%oka_file.container.data_dirnames%']
#
#    Oka\FileBundle\Command\ImageDominantColorCommand:
#        arguments: ['@oka_file.image_manager', '@oka_file.uploaded_image.manager', '%oka_file.image.uploaded.detect_dominant_color%']
#
#    Oka\FileBundle\Command\UpgradeImageCommand:
#        arguments: ['@oka_file.image_manager', '@oka_file.uploaded_image.manager', '%oka_file.image.uploaded.detect_dominant_color%']
