services:
    oka_file.container_parameter_bag:
        public: false
        class: Oka\FileBundle\Service\ContainerParameterBag
        arguments: [[]]

    oka_file.storage_handler.default:
        public: false
        class: Oka\FileBundle\Service\NativeFileStorageHandler
        arguments: ['%oka_file.storage.root_path%', '%oka_file.storage.webserver%', '@oka_file.container_parameter_bag']

    oka_file.storage.image_manipulator:
        public: true
        class: Oka\FileBundle\Service\ImageManipulator
        arguments: ['']

    Oka\FileBundle\Service\ImageManipulator:
        public: true
        alias: oka_file.storage.image_manipulator

    Oka\FileBundle\Model\FileStorageHandlerInterface:
        public: false
        alias: oka_file.storage_handler

    Oka\FileBundle\EventListener\UploadedImageListener:
        arguments: ['@oka_file.storage.image_manipulator', '@oka_file.container_parameter_bag', '%oka_file.storage.image.dominant_color%', '%oka_file.storage.image.thumbnail_factory%']
        tags:
          - { name: kernel.event_subscriber }
