Oka\FileBundle\Model\Image:
    properties:
        uploadedFile:
            - Image:
                mimeTypes: ['image/*', 'application/x-shockwave-flash', 'application/octet-stream']
                mimeTypesMessage: 'Only image files are accepted.'
                groups: ['Upload', 'Default']
