services:
# Utils
    oka_file.doctrine_behaviors.reflection.class_analyzer:
        class:  Oka\FileBundle\DoctrineBehaviors\Reflection\ClassAnalyzer
        public: false

# Doctrine behaviors
    oka_file.doctrine_behaviors.abstract_listener:
        public: false
        abstract: true
        class:  Oka\FileBundle\DoctrineBehaviors\Common\AbstractListener
        arguments: [ [], '' ]
        calls:
          - [ setClassAnalyzer, [ '@oka_file.doctrine_behaviors.reflection.class_analyzer' ] ]
          - [ setRecursive, [ '%oka_file.doctrine_behaviors.reflection.is_recursive%' ] ]
