oka_file_image_list:
    path:     /images/list
    defaults: { _controller: 'OkaFileBundle:Image:list' }
    methods: GET

oka_file_image_create:
    path:     /images/create
    defaults: { _controller: 'OkaFileBundle:Image:create' }
    methods: [GET, POST]

oka_file_image_show:
    path:     /images/show/{id}
    defaults: { _controller: 'OkaFileBundle:Image:show' }
    methods: GET

oka_file_image_update:
    path:     /images/update/{id}
    defaults: { _controller: 'OkaFileBundle:Image:update' }
    methods: [GET, POST]

oka_file_image_delete:
    path:     /images/delete/{id}
    defaults: { _controller: 'OkaFileBundle:Image:delete' }
    methods: [GET, DELETE]

oka_file_image_upload:
    path:     /images/upload
    defaults: { _controller: 'OkaFileBundle:Image:upload' }
    methods: [GET, POST]

oka_file_image_snapshot:
    path:     /images/snapshot
    defaults: { _controller: 'OkaFileBundle:Image:snapshot' }

oka_file_image_delete_size:
    path:     /images/delete/{id}/size/{width}/{height}
    defaults: { _controller: 'OkaFileBundle:Image:deleteSize' }
    methods: [GET, DELETE]
